[project]
name = "mathematical-entity-extraction"
version = "0.1.0"
description = "Mathematical Entity Extraction"
readme = "README.md"
requires-python = ">=3.10"

dependencies = ["ipykernel",
"torch", 
"transformers", 
"vllm",
"pandas",
"scikit-learn"]
